project:
  type: website

website:
  title: "Jacky's Website"
  favicon: figures/lemon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: qmd/about.qmd
        text: About
      - href: qmd/projects.qmd
        text: Projects
      - href: qmd/publications.qmd
        text: Publications
      - href: qmd/contact.qmd
        text: Contact
    right:
      - icon: github
        href: 'https://github.com/mxngjxa'
      - icon: linkedin
        href: 'https://linkedin.com/in/mingjia-jacky-guan'
  page-footer:
    center:
      - text: '© 2025 MG Technologies, LLC'
      - icon: github
        href: 'https://github.com/mxngjxa'
      - icon: linkedin
        href: 'https://linkedin.com/in/mingjia-jacky-guan'
    border: false

format:
  html:
    theme:
      light: minty
      dark: brand.scss
    mainfont: "Roboto Mono"
    monofont: "MesloLGS NF"
    toc: true
    number-sections: true