project:
  type: website

website:
  title: "Jacky's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - publications.qmd
      - contact.qmd
    right:
      - icon: github
        href: 'https://github.com/mxngjxa'
      - icon: linkedin
        href: 'https://linkedin.com/in/mingjia-jacky-guan'
  page-footer:
    center:
      - text: '© 2025 MG Technologies, LLC'
      - icon: github
        href: 'https://github.com/mxngjxa'
      - icon: linkedin
        href: 'https://linkedin.com/in/mingjia-jacky-guan'
    border: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true